In [558]:
import pandas as pd
import numpy as np
from datetime import datetime

In [560]:
df=pd.read_csv("synthetic_job_applications.csv")
df

,company_name,job_role,applied_date,website,status,created_at,notes
0,Neal-Sims,Deep Learning Engineer,01-03-2025,AngelList,Applied,23-06-2025 03:22,Middle four lose bit ever scene.
1,James Inc,ML Engineer,23-02-2025,Internshala,Followed-Up,22-06-2025 21:52,Human rule too position sound skin one.
2,Bush PLC,AI Engineer,14-03-2025,Naukri,Interview,17-02-2025 20:06,Break deep idea its person third catch factor.
3,"Padilla, Price and Smith",NLP Engineer,03-07-2025,AngelList,Rejected,20-05-2025 19:03,Thousand yeah must business our carry painting.
4,Brown Inc,Computer Vision Engineer,18-07-2025,Other,Followed-Up,15-04-2025 08:28,Their sea attention involve involve tough oppo...
...,...,...,...,...,...,...,...
120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [562]:
df = df.dropna(how="all")

In [564]:
df.tail(10)

,company_name,job_role,applied_date,website,status,created_at,notes
105,Capgemini,Data Engineer,12-07-2025,Indeed,Rejected,12-07-2025 15:08,Automated rejection email received
106,"Wipro, delhi",Business Analyst,14-07-2025,LinkedIn,Rejected,14-07-2025 09:59,Awaiting feedback from panel
107,Accenture,Associate Data Scientist,16-07-2025,Company Website,Rejected,16-07-2025 17:42,Did not clear coding round
108,Cognizant,ML Engineer Intern,18-07-2025,Naukri,Rejected,18-07-2025 12:20,Invited for HR discussion
109,HCL,Data Analyst,20-07-2025,LinkedIn,Rejected,20-07-2025 16:35,Position closed before final round
110,"Freshworks, Chennai",Data Engineer,22-07-2025,Company Website,Interview,22-07-2025 11:05,Called for technical interview
111,"Razorpay, Bangalore",AI Research Intern,24-07-2025,LinkedIn,Rejected,24-07-2025 13:27,Role filled before my application review
112,"Mindtree, Noida",Data Scientist,26-07-2025,Indeed,Interview,26-07-2025 10:55,Completed first technical round
113,"Zerodha, Bangalore",Machine Learning Engineer,28-07-2025,Naukri,Rejected,28-07-2025 15:44,Rejection mail received after HR screening
114,"InMobi, Gurgaon",Junior Data Analyst,30-07-2025,Company Website,Interview,30-07-2025 09:39,Waiting for second round update

In [566]:
df.isna().sum()

company_name    0
job_role        0
applied_date    0
website         0
status          0
created_at      0
notes           0
dtype: int64

In [568]:
df

,company_name,job_role,applied_date,website,status,created_at,notes
0,Neal-Sims,Deep Learning Engineer,01-03-2025,AngelList,Applied,23-06-2025 03:22,Middle four lose bit ever scene.
1,James Inc,ML Engineer,23-02-2025,Internshala,Followed-Up,22-06-2025 21:52,Human rule too position sound skin one.
2,Bush PLC,AI Engineer,14-03-2025,Naukri,Interview,17-02-2025 20:06,Break deep idea its person third catch factor.
3,"Padilla, Price and Smith",NLP Engineer,03-07-2025,AngelList,Rejected,20-05-2025 19:03,Thousand yeah must business our carry painting.
4,Brown Inc,Computer Vision Engineer,18-07-2025,Other,Followed-Up,15-04-2025 08:28,Their sea attention involve involve tough oppo...
...,...,...,...,...,...,...,...
110,"Freshworks, Chennai",Data Engineer,22-07-2025,Company Website,Interview,22-07-2025 11:05,Called for technical interview
111,"Razorpay, Bangalore",AI Research Intern,24-07-2025,LinkedIn,Rejected,24-07-2025 13:27,Role filled before my application review
112,"Mindtree, Noida",Data Scientist,26-07-2025,Indeed,Interview,26-07-2025 10:55,Completed first technical round
113,"Zerodha, Bangalore",Machine Learning Engineer,28-07-2025,Naukri,Rejected,28-07-2025 15:44,Rejection mail received after HR screening
114,"InMobi, Gurgaon",Junior Data Analyst,30-07-2025,Company Website,Interview,30-07-2025 09:39,Waiting for second round update

In [570]:
# Copy dataset to avoid modifying original
df_model = df.copy()

# 1. Convert dates to datetime format
df_model['applied_date'] = pd.to_datetime(df_model['applied_date'],format="%d-%m-%Y", errors='coerce')
df_model['created_at'] = pd.to_datetime(df_model['created_at'], errors='coerce')

# Extract date-based features
df_model['applied_month'] = df_model['applied_date'].dt.month
df_model['applied_day'] = df_model['applied_date'].dt.day
df_model['applied_weekday'] = df_model['applied_date'].dt.weekday

C:\Users\mypc\AppData\Local\Temp\ipykernel_15936\232622494.py:6: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_model['created_at'] = pd.to_datetime(df_model['created_at'], errors='coerce')

In [572]:
# Keep only interview and rejected statuses
df_filtered = df_model[df_model['status'].str.strip().str.lower().isin(['interview', 'rejected'])]

# Convert to binary target
df_filtered['interview_received'] = df_filtered['status'].apply(lambda x: 1 if x.strip().lower() == 'interview' else 0)

# 3. Drop unused columns (notes for now)
df_filtered = df_filtered.drop(columns=['notes', 'applied_date', 'created_at', 'status'])

C:\Users\mypc\AppData\Local\Temp\ipykernel_15936\4148662629.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['interview_received'] = df_filtered['status'].apply(lambda x: 1 if x.strip().lower() == 'interview' else 0)

In [574]:
# 4. Encode categorical variables using one-hot encoding
df_model_encoded = pd.get_dummies(df_filtered, columns=['company_name', 'job_role', 'website'], drop_first=True)

In [576]:
# Convert all boolean columns to int (0/1)
df_model_encoded = df_model_encoded.astype(int)

In [578]:
df_model_encoded

,applied_month,applied_day,applied_weekday,interview_received,company_name_Amazon,company_name_Brown Inc,"company_name_Bullock, Church and Miller",company_name_Bush PLC,company_name_Capgemini,company_name_Carlson and Sons,...,job_role_Other,job_role_Research Scientist,website_Company Website,website_Glassdoor,website_Hirect,website_Indeed,website_Internshala,website_LinkedIn,website_Naukri,website_Other
2,3,14,4,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,7,3,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,7,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
12,8,4,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
14,7,17,3,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,6,30,0,1,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
17,3,8,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18,7,13,6,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,4,16,2,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
24,3,24,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
25,4,2,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,2,6,3,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
39,2,7,4,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
46,2,10,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
48,7,6,6,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
54,5,4,6,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
56,3,22,5,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
57,8,3,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60,5,23,4,1,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
65,6,22,6,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
66,4,25,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75,2,26,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
76,5,7,2,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
81,3,22,5,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
82,3,11,1,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
86,6,17,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
93,3,9,6,1,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
95,5,14,2,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
98,8,1,4,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
100,7,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
101,7,3,3,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
102,7,5,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
103,7,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
104,7,10,3,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
105,7,12,5,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
106,7,14,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
107,7,16,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
108,7,18,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
109,7,20,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
110,7,22,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
111,7,24,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
112,7,26,5,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
113,7,28,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
114,7,30,2,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [580]:
# After encoding
df_model_encoded.columns = df_model_encoded.columns.str.strip()

In [582]:
df_model_encoded.columns

Index(['applied_month', 'applied_day', 'applied_weekday', 'interview_received',
       'company_name_Amazon', 'company_name_Brown Inc',
       'company_name_Bullock, Church and Miller', 'company_name_Bush PLC',
       'company_name_Capgemini', 'company_name_Carlson and Sons',
       'company_name_Cognizant', 'company_name_Flores and Sons',
       'company_name_Franklin Inc', 'company_name_Freshworks, Chennai',
       'company_name_Glover Group', 'company_name_Google, washington DC',
       'company_name_HCL', 'company_name_Hall, Dougherty and Greene',
       'company_name_Harvey LLC', 'company_name_Hayes-Mathews',
       'company_name_InMobi, Gurgaon', 'company_name_Infosys, kerala',
       'company_name_Johnson Inc', 'company_name_Jones Inc',
       'company_name_Jordan-Tucker',
       'company_name_Marquez, Robertson and Castro',
       'company_name_Martinez and Sons', 'company_name_Mcdonald Group',
       'company_name_Microsoft', 'company_name_Miller, Berry and Strickland',
       'company_name_Miller, Price and Kelley', 'company_name_Mindtree, Noida',
       'company_name_Mitchell and Sons', 'company_name_Morales PLC',
       'company_name_Oliver, Young and Morris',
       'company_name_Padilla, Price and Smith', 'company_name_Ramos LLC',
       'company_name_Razorpay, Bangalore',
       'company_name_Stewart, Barnett and Coleman', 'company_name_TCS, london',
       'company_name_Turner LLC', 'company_name_Valdez, Washington and Chen',
       'company_name_Vazquez LLC', 'company_name_Villa and Sons',
       'company_name_Watts and Sons', 'company_name_Wipro, delhi',
       'company_name_Zerodha, Bangalore', 'job_role_AI Research Intern',
       'job_role_Associate Data Scientist', 'job_role_Business Analyst',
       'job_role_Computer Vision Engineer', 'job_role_Data Analyst',
       'job_role_Data Engineer', 'job_role_Data Scientist',
       'job_role_Deep Learning Engineer', 'job_role_Junior Data Analyst',
       'job_role_Junior Data Scientist', 'job_role_ML Engineer',
       'job_role_ML Engineer Intern', 'job_role_Machine Learning Engineer',
       'job_role_NLP Engineer', 'job_role_Other',
       'job_role_Research Scientist', 'website_Company Website',
       'website_Glassdoor', 'website_Hirect', 'website_Indeed',
       'website_Internshala', 'website_LinkedIn', 'website_Naukri',
       'website_Other'],
      dtype='object')

In [584]:
print(df_model_encoded['interview_received'].unique())

[1 0]

In [586]:
for col in df_model_encoded.columns:
    print(f"Column: {col}")
    print(df_model_encoded[col].unique())
    print("-" * 50)

Column: applied_month
[3 7 5 8 6 4 2]
--------------------------------------------------
Column: applied_day
[14  3  7  4 17 30  8 13 16 24  2  6 10 22 23 25 26 11  9  1  5 12 18 20
 28]
--------------------------------------------------
Column: applied_weekday
[4 3 2 0 5 6 1]
--------------------------------------------------
Column: interview_received
[1 0]
--------------------------------------------------
Column: company_name_Amazon
[0 1]
--------------------------------------------------
Column: company_name_Brown Inc
[0 1]
--------------------------------------------------
Column: company_name_Bullock, Church and Miller
[0 1]
--------------------------------------------------
Column: company_name_Bush PLC
[1 0]
--------------------------------------------------
Column: company_name_Capgemini
[0 1]
--------------------------------------------------
Column: company_name_Carlson and Sons
[0 1]
--------------------------------------------------
Column: company_name_Cognizant
[0 1]
--------------------------------------------------
Column: company_name_Flores and Sons
[0 1]
--------------------------------------------------
Column: company_name_Franklin Inc
[0 1]
--------------------------------------------------
Column: company_name_Freshworks, Chennai
[0 1]
--------------------------------------------------
Column: company_name_Glover Group
[0 1]
--------------------------------------------------
Column: company_name_Google, washington DC
[0 1]
--------------------------------------------------
Column: company_name_HCL
[0 1]
--------------------------------------------------
Column: company_name_Hall, Dougherty and Greene
[0 1]
--------------------------------------------------
Column: company_name_Harvey LLC
[0 1]
--------------------------------------------------
Column: company_name_Hayes-Mathews
[0 1]
--------------------------------------------------
Column: company_name_InMobi, Gurgaon
[0 1]
--------------------------------------------------
Column: company_name_Infosys, kerala
[0 1]
--------------------------------------------------
Column: company_name_Johnson Inc
[0 1]
--------------------------------------------------
Column: company_name_Jones Inc
[0 1]
--------------------------------------------------
Column: company_name_Jordan-Tucker
[0 1]
--------------------------------------------------
Column: company_name_Marquez, Robertson and Castro
[0 1]
--------------------------------------------------
Column: company_name_Martinez and Sons
[0 1]
--------------------------------------------------
Column: company_name_Mcdonald Group
[0 1]
--------------------------------------------------
Column: company_name_Microsoft
[0 1]
--------------------------------------------------
Column: company_name_Miller, Berry and Strickland
[0 1]
--------------------------------------------------
Column: company_name_Miller, Price and Kelley
[0 1]
--------------------------------------------------
Column: company_name_Mindtree, Noida
[0 1]
--------------------------------------------------
Column: company_name_Mitchell and Sons
[0 1]
--------------------------------------------------
Column: company_name_Morales PLC
[0 1]
--------------------------------------------------
Column: company_name_Oliver, Young and Morris
[0 1]
--------------------------------------------------
Column: company_name_Padilla, Price and Smith
[0 1]
--------------------------------------------------
Column: company_name_Ramos LLC
[0 1]
--------------------------------------------------
Column: company_name_Razorpay, Bangalore
[0 1]
--------------------------------------------------
Column: company_name_Stewart, Barnett and Coleman
[0 1]
--------------------------------------------------
Column: company_name_TCS, london
[0 1]
--------------------------------------------------
Column: company_name_Turner LLC
[0 1]
--------------------------------------------------
Column: company_name_Valdez, Washington and Chen
[0 1]
--------------------------------------------------
Column: company_name_Vazquez LLC
[0 1]
--------------------------------------------------
Column: company_name_Villa and Sons
[0 1]
--------------------------------------------------
Column: company_name_Watts and Sons
[0 1]
--------------------------------------------------
Column: company_name_Wipro, delhi
[0 1]
--------------------------------------------------
Column: company_name_Zerodha, Bangalore
[0 1]
--------------------------------------------------
Column: job_role_AI Research Intern
[0 1]
--------------------------------------------------
Column: job_role_Associate Data Scientist
[0 1]
--------------------------------------------------
Column: job_role_Business Analyst
[0 1]
--------------------------------------------------
Column: job_role_Computer Vision Engineer
[0 1]
--------------------------------------------------
Column: job_role_Data Analyst
[0 1]
--------------------------------------------------
Column: job_role_Data Engineer
[0 1]
--------------------------------------------------
Column: job_role_Data Scientist
[0 1]
--------------------------------------------------
Column: job_role_Deep Learning Engineer
[0 1]
--------------------------------------------------
Column: job_role_Junior Data Analyst
[0 1]
--------------------------------------------------
Column: job_role_Junior Data Scientist
[0 1]
--------------------------------------------------
Column: job_role_ML Engineer
[0 1]
--------------------------------------------------
Column: job_role_ML Engineer Intern
[0 1]
--------------------------------------------------
Column: job_role_Machine Learning Engineer
[0 1]
--------------------------------------------------
Column: job_role_NLP Engineer
[0 1]
--------------------------------------------------
Column: job_role_Other
[0 1]
--------------------------------------------------
Column: job_role_Research Scientist
[0 1]
--------------------------------------------------
Column: website_Company Website
[0 1]
--------------------------------------------------
Column: website_Glassdoor
[0 1]
--------------------------------------------------
Column: website_Hirect
[0 1]
--------------------------------------------------
Column: website_Indeed
[0 1]
--------------------------------------------------
Column: website_Internshala
[0 1]
--------------------------------------------------
Column: website_LinkedIn
[0 1]
--------------------------------------------------
Column: website_Naukri
[1 0]
--------------------------------------------------
Column: website_Other
[0 1]
--------------------------------------------------

In [588]:
df_model_encoded.head()

,applied_month,applied_day,applied_weekday,interview_received,company_name_Amazon,company_name_Brown Inc,"company_name_Bullock, Church and Miller",company_name_Bush PLC,company_name_Capgemini,company_name_Carlson and Sons,...,job_role_Other,job_role_Research Scientist,website_Company Website,website_Glassdoor,website_Hirect,website_Indeed,website_Internshala,website_LinkedIn,website_Naukri,website_Other
2,3,14,4,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,7,3,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,5,7,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
12,8,4,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
14,7,17,3,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [590]:
# Save as CSV
df_model_encoded.to_csv("model_ready_job_applications.csv", index=False, quotechar='"')

# Modelling!!!!!!!!!

In [593]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score
import joblib

# 1. Load your preprocessed dataset (must have interview_received as target)
df = pd.read_csv("model_ready_job_applications.csv")

# Separate features & target
X = df.drop(columns=['interview_received'])
y = df['interview_received']

# 2. Split into train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 3. Train Random Forest
model_1 = RandomForestClassifier(class_weight='balanced', random_state=42)
model_1.fit(X_train, y_train)

# 4. Evaluate
y_pred = model_1.predict(X_test)
y_proba = model_1.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred,zero_division=0))
print("AUC Score:", roc_auc_score(y_test, y_proba))

              precision    recall  f1-score   support

           0       0.75      0.60      0.67         5
           1       0.60      0.75      0.67         4

    accuracy                           0.67         9
   macro avg       0.68      0.68      0.67         9
weighted avg       0.68      0.67      0.67         9

AUC Score: 0.8

In [595]:
joblib.dump(X.columns.tolist(), "feature_columns.pkl")
print("âœ… Feature saved as feature_columns.pkl")

âœ… Feature saved as feature_columns.pkl

In [597]:
df

,applied_month,applied_day,applied_weekday,interview_received,company_name_Amazon,company_name_Brown Inc,"company_name_Bullock, Church and Miller",company_name_Bush PLC,company_name_Capgemini,company_name_Carlson and Sons,...,job_role_Other,job_role_Research Scientist,website_Company Website,website_Glassdoor,website_Hirect,website_Indeed,website_Internshala,website_LinkedIn,website_Naukri,website_Other
0,3,14,4,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
1,7,3,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,5,7,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,8,4,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,7,17,3,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5,6,30,0,1,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
6,3,8,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
7,7,13,6,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,4,16,2,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9,3,24,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,4,2,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,2,6,3,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,2,7,4,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13,2,10,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
14,7,6,6,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
15,5,4,6,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
16,3,22,5,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
17,8,3,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,5,23,4,1,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
19,6,22,6,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
20,4,25,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
21,2,26,2,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
22,5,7,2,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23,3,22,5,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,3,11,1,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
25,6,17,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
26,3,9,6,1,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
27,5,14,2,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,8,1,4,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
29,7,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
30,7,3,3,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
31,7,5,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
32,7,7,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
33,7,10,3,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
34,7,12,5,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
35,7,14,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
36,7,16,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
37,7,18,4,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
38,7,20,6,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
39,7,22,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
40,7,24,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
41,7,26,5,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
42,7,28,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
43,7,30,2,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [599]:
y.value_counts()

interview_received
0    23
1    21
Name: count, dtype: int64

In [232]:
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, classification_report
import pandas as pd

 

# ----- Models to compare -----
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
}

# ----- Train & Evaluate -----
results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1] if hasattr(model, "predict_proba") else None

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1 Score": f1_score(y_test, y_pred, zero_division=0),
        "AUC": roc_auc_score(y_test, y_proba) if y_proba is not None else "N/A"
    })

# ----- Show Results -----
df_results = pd.DataFrame(results)
print(df_results.sort_values(by="F1 Score", ascending=False))

                 Model  Accuracy  Precision  Recall  F1 Score   AUC
1    Gradient Boosting  0.888889   0.800000     1.0  0.888889  0.80
0  Logistic Regression  0.777778   0.666667     1.0  0.800000  0.80
2              XGBoost  0.444444   0.400000     0.5  0.444444  0.55

C:\Users\mypc\anaconda3\Lib\site-packages\xgboost\core.py:158: UserWarning: [18:45:26] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

# samplee

In [601]:
# import joblib

# df = pd.read_csv("model_ready_job_applications.csv")

# X = pd.get_dummies(df.drop("interview_received", axis=1))  # example
# y = df["interview_received"]

In [603]:
# # 4. Evaluate
# y_pred = model.predict(X_test)
# y_proba = model.predict_proba(X_test)[:, 1]

# print(classification_report(y_test, y_pred, zero_division=0))
# print("AUC Score:", roc_auc_score(y_test, y_proba))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         4

    accuracy                           1.00         9
   macro avg       1.00      1.00      1.00         9
weighted avg       1.00      1.00      1.00         9

AUC Score: 1.0

In [ ]:
# joblib.dump(X.columns.tolist(), "feature_columns.pkl")
# print("âœ… Feature saved as feature_columns.pkl")

In [367]:
# import joblib

# # After preprocessing and before training
# X = pd.get_dummies(df.drop("interview_received", axis=1))  # example
# y = df["interview_received"]

In [369]:
# # Save feature columns
# joblib.dump(X.columns.tolist(), "feature_columns.pkl")
# print("âœ… Feature saved as feature_columns.pkl")

âœ… Feature saved as feature_columns.pkl

In [371]:
# # Train model
# from sklearn.ensemble import GradientBoostingClassifier
# model = GradientBoostingClassifier()
# model.fit(X, y)

# # 4. Evaluate
# y_pred = model.predict(X_test)
# y_proba = model.predict_proba(X_test)[:, 1]

# print(classification_report(y_test, y_pred, zero_division=0))
# print("AUC Score:", roc_auc_score(y_test, y_proba))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         4

    accuracy                           1.00         9
   macro avg       1.00      1.00      1.00         9
weighted avg       1.00      1.00      1.00         9

AUC Score: 1.0

In [ ]:
# # Save model
# joblib.dump(model, "Interview_predictor.pkl")

In [ ]:
# print(X.columns)

In [607]:
print(df.shape)

(44, 71)

In [250]:

model = GradientBoostingClassifier(random_state=42)
model.fit(X_train, y_train)

# 4. Evaluate
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred, zero_division=0))
print("AUC Score:", roc_auc_score(y_test, y_proba))

              precision    recall  f1-score   support

           0       1.00      0.80      0.89         5
           1       0.80      1.00      0.89         4

    accuracy                           0.89         9
   macro avg       0.90      0.90      0.89         9
weighted avg       0.91      0.89      0.89         9

AUC Score: 0.8

In [252]:
# # 5. Save model for Streamlit
joblib.dump(model, "interview_predictor.pkl")
print("âœ… Model saved as interview_predictor.pkl")

âœ… Model saved as interview_predictor.pkl

In [1]:
! pip list

Package                           Version
--------------------------------- ------------------
absl-py                           2.1.0
aext-assistant                    4.1.0
aext-assistant-server             4.1.0
aext-core                         4.1.0
aext-core-server                  4.1.0
aext-panels                       4.1.0
aext-panels-server                4.1.0
aext-project-filebrowser-server   4.1.0
aext-share-notebook               4.1.0
aext-share-notebook-server        4.1.0
aext-shared                       4.1.0
aext-toolbox                      4.1.0
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
alembic                           1.13.3
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.4.2
anaconda-client                   1.13.0
anaconda-cloud-auth               0.7.2
anaconda-navigator                2.6.3
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data                 0.2024.9.2.0.33.23
asttokens                         3.0.0
astunparse                        1.6.3
async-lru                         2.0.4
atomicwrites                      1.4.0
attrs                             23.1.0
Automat                           20.2.0
autopep8                          2.0.4
Babel                             2.11.0
bcrypt                            3.2.0
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
black                             24.8.0
bleach                            4.1.0
blinker                           1.6.2
bokeh                             3.6.0
boltons                           23.0.0
botocore                          1.34.69
Bottleneck                        1.3.7
Brotli                            1.0.9
cached-property                   1.5.2
cachetools                        5.3.3
certifi                           2025.1.31
cffi                              1.17.1
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
cmake                             3.31.6
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.2
comtypes                          1.4.10
conda                             25.1.1
conda-build                       24.9.0
conda-content-trust               0.2.0
conda_index                       0.5.0
conda-libmamba-solver             24.9.0
conda-pack                        0.7.1
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
conda-repo-cli                    1.0.114
conda-token                       0.5.0+1.g2209e04
constantly                        23.10.4
contourpy                         1.2.0
cookiecutter                      2.6.0
cryptography                      43.0.0
cssselect                         1.2.0
cycler                            0.11.0
cytoolz                           0.12.2
dask                              2024.8.1
dask-expr                         1.1.11
datashader                        0.16.3
debugpy                           1.8.13
decorator                         5.2.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.3.8
distributed                       2024.8.1
distro                            1.9.0
dlib                              19.24.2
docstring-to-markdown             0.11
docutils                          0.18.1
et-xmlfile                        1.1.0
executing                         2.2.0
face-recognition                  1.3.0
face_recognition_models           0.3.0
fastjsonschema                    2.16.2
filelock                          3.13.1
flake8                            7.0.0
Flask                             3.0.3
flatbuffers                       25.2.10
fonttools                         4.51.0
frozendict                        2.4.2
frozenlist                        1.4.0
fsspec                            2024.6.1
gast                              0.6.0
gensim                            4.3.3
gitdb                             4.0.7
GitPython                         3.1.43
google-pasta                      0.2.0
greenlet                          3.0.1
grpcio                            1.70.0
h11                               0.14.0
h5py                              3.13.0
HeapDict                          1.0.1
holoviews                         1.19.1
httpcore                          1.0.2
httpx                             0.27.0
huggingface-hub                   0.30.2
hvplot                            0.11.0
hyperlink                         21.0.0
idna                              3.7
imagecodecs                       2024.6.1
imageio                           2.33.1
imagesize                         1.4.1
imbalanced-learn                  0.12.3
importlib-metadata                7.0.1
incremental                       22.10.0
inflection                        0.5.1
iniconfig                         1.1.1
intake                            2.0.7
intervaltree                      3.1.0
ipykernel                         6.29.5
ipython                           9.0.2
ipython-genutils                  0.2.0
ipython_pygments_lexers           1.1.1
ipywidgets                        7.8.1
isort                             5.13.2
itemadapter                       0.3.0
itemloaders                       1.1.0
itsdangerous                      2.2.0
jaraco.classes                    3.2.1
jax                               0.5.3
jaxlib                            0.5.3
jedi                              0.19.2
jellyfish                         1.0.1
Jinja2                            3.1.4
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.6
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.7.1
jupyter                           1.0.0
jupyter_client                    8.6.3
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.0
jupyter_server                    2.14.1
jupyter_server_terminals          0.4.4
jupyterlab                        4.2.5
jupyterlab-pygments               0.1.2
jupyterlab_server                 2.27.3
jupyterlab-widgets                1.0.0
keras                             3.8.0
keyring                           24.3.1
kiwisolver                        1.4.4
lazy_loader                       0.4
lazy-object-proxy                 1.10.0
lckr_jupyterlab_variableinspector 3.1.0
libarchive-c                      5.1
libclang                          18.1.1
libmambapy                        1.5.8
lightgbm                          4.6.0
linkify-it-py                     2.0.0
llvmlite                          0.44.0
lmdb                              1.4.1
locket                            1.0.0
lxml                              5.3.1
lz4                               4.3.2
Mako                              1.2.3
Markdown                          3.4.1
markdown-it-py                    2.2.0
MarkupSafe                        2.1.3
matplotlib                        3.9.2
matplotlib-inline                 0.1.7
mccabe                            0.7.0
mdit-py-plugins                   0.3.0
mdurl                             0.1.0
mediapipe                         0.10.21
menuinst                          2.1.2
mistune                           2.0.4
mkl_fft                           1.3.10
mkl_random                        1.2.7
mkl-service                       2.4.0
ml-dtypes                         0.4.1
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.3
multidict                         6.0.4
multipledispatch                  0.6.0
mypy                              1.11.2
mypy-extensions                   1.0.0
namex                             0.0.8
navigator-updater                 0.5.1
nb_conda_kernels                  2.5.2
nbclient                          0.8.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.3
nltk                              3.9.1
notebook                          7.2.2
notebook_shim                     0.2.3
numba                             0.61.0
numexpr                           2.8.7
numpy                             1.26.4
numpydoc                          1.7.0
opencv-contrib-python             4.11.0.86
opencv-python                     4.11.0.86
opencv-python-headless            4.11.0.86
openpyxl                          3.1.5
opt_einsum                        3.4.0
optree                            0.14.0
overrides                         7.4.0
packaging                         24.2
pandas                            2.2.2
pandocfilters                     1.5.0
panel                             1.5.2
param                             2.1.1
paramiko                          2.8.1
parsel                            1.8.1
parso                             0.8.4
partd                             1.4.1
pathspec                          0.10.3
patsy                             0.5.6
pexpect                           4.8.0
pickleshare                       0.7.5
pillow                            10.4.0
pip                               24.2
pkce                              1.0.3
pkginfo                           1.10.0
platformdirs                      4.3.7
plotly                            5.24.1
pluggy                            1.0.0
ply                               3.11
prometheus-client                 0.14.1
prompt_toolkit                    3.0.50
Protego                           0.1.16
protobuf                          4.25.3
psutil                            7.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyarrow                           13.0.0
pyarrow-hotfix                    0.6
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
PyAudio                           0.2.14
pycodestyle                       2.11.1
pycosat                           0.6.6
pycparser                         2.21
pyct                              0.5.0
pycurl                            7.45.3
pydantic                          2.8.2
pydantic_core                     2.20.1
pydantic-settings                 2.6.1
pydeck                            0.8.0
PyDispatcher                      2.0.5
pydocstyle                        6.3.0
pyerfa                            2.0.1.4
pyflakes                          3.2.0
Pygments                          2.19.1
PyJWT                             2.8.0
pylint                            2.16.2
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
PyNaCl                            1.5.0
pyodbc                            5.1.0
pyOpenSSL                         24.2.1
pyparsing                         3.1.2
pypiwin32                         223
PyQt5                             5.15.10
PyQt5-sip                         12.13.0
PyQtWebEngine                     5.15.6
PySocks                           1.7.1
pytesseract                       0.3.13
pytest                            7.4.4
python-dateutil                   2.9.0.post0
python-dotenv                     0.21.0
python-json-logger                2.0.7
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-server                 1.10.0
python-slugify                    5.0.2
pytoolconfig                      1.2.6
pyttsx3                           2.98
pytz                              2024.1
pyviz_comms                       3.0.2
PyWavelets                        1.7.0
pywin32                           310
pywin32-ctypes                    0.2.2
pywinpty                          2.0.10
PyYAML                            6.0.1
pyzmq                             26.3.0
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.3.1
qtconsole                         5.5.1
QtPy                              2.4.1
queuelib                          1.6.2
readchar                          4.0.5
referencing                       0.30.2
regex                             2024.9.11
requests                          2.32.3
requests-file                     1.5.1
requests-toolbelt                 1.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.7.1
rope                              1.12.0
rpds-py                           0.10.6
Rtree                             1.0.1
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruamel-yaml-conda                 0.17.21
s3fs                              2024.6.1
safetensors                       0.5.3
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.13.1
Scrapy                            2.11.1
seaborn                           0.13.2
semver                            3.0.2
Send2Trash                        1.8.2
sentencepiece                     0.2.0
sentry-sdk                        2.18.0
service-identity                  18.1.0
setuptools                        75.1.0
shellingham                       1.5.0
sip                               6.7.12
six                               1.17.0
smart-open                        5.2.1
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
sounddevice                       0.5.1
soupsieve                         2.5
SpeechRecognition                 3.14.2
Sphinx                            7.3.7
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.10
spyder                            5.5.1
spyder-kernels                    2.5.0
SQLAlchemy                        2.0.34
stack-data                        0.6.3
statsmodels                       0.14.2
streamlit                         1.37.1
sympy                             1.14.0
tables                            3.9.2
tabulate                          0.9.0
tblib                             1.7.0
tenacity                          8.2.3
tensorboard                       2.18.0
tensorboard-data-server           0.7.2
tensorflow                        2.18.0
tensorflow_intel                  2.18.0
termcolor                         2.5.0
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.2.1
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2023.4.12
tinycss2                          1.2.1
tldextract                        5.1.2
tokenizers                        0.21.1
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.11.1
toolz                             0.12.0
torch                             2.7.0
torchvision                       0.22.0
tornado                           6.4.2
tqdm                              4.66.5
traitlets                         5.14.3
transformers                      4.51.3
truststore                        0.8.0
Twisted                           23.10.0
twisted-iocpsupport               1.0.2
typer                             0.9.0
typing_extensions                 4.11.0
tzdata                            2023.3
uc-micro-py                       1.0.1
ujson                             5.10.0
unicodedata2                      15.1.0
Unidecode                         1.3.8
urllib3                           2.2.3
w3lib                             2.1.2
watchdog                          4.0.1
wcwidth                           0.2.13
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.0.3
whatthepatch                      1.0.2
wheel                             0.44.0
widgetsnbextension                3.6.6
win-inet-pton                     1.1.0
wrapt                             1.14.1
xarray                            2023.6.0
xgboost                           2.1.4
xlwings                           0.32.1
xyzservices                       2022.9.0
yapf                              0.40.2
yarl                              1.11.0
zict                              3.0.0
zipp                              3.17.0
zope.interface                    5.4.0
zstandard                         0.23.0